//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KulturMerkezi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CenterContainer : DbContext
    {
        public CenterContainer()
            : base("name=CenterContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Egitimler> EgitimlerSet { get; set; }
        public virtual DbSet<Egitmenler> EgitmenlerSet { get; set; }
        public virtual DbSet<Subeler> SubelerSet { get; set; }
        public virtual DbSet<Ogrenciler> OgrencilerSet { get; set; }
        public virtual DbSet<Kullanicilar> KullanicilarSet { get; set; }
    }
}
