//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KulturMerkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitmenler
    {
        public int EgitmenNo { get; set; }
        public string EgitmenAdi { get; set; }
        public string EgitmenSifre { get; set; }
        public string EgitmenMail { get; set; }
        public string EgitmenTelefon { get; set; }
        public string EgitmenAlani { get; set; }
        public int SubeNo { get; set; }
    
        public virtual Subeler Subeler { get; set; }
    }
}
