//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KulturMerkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitimler
    {
        public int EgitimNo { get; set; }
        public string EgitimAdi { get; set; }
        public int EgitimSaati { get; set; }
        public string EgitimTuru { get; set; }
        public decimal EgitimUcreti { get; set; }
        public string EgitimGunu { get; set; }
        public int SubeNo { get; set; }
    
        public virtual Subeler Subeler { get; set; }
    }
}
