//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KulturMerkezi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subeler()
        {
            this.Egitimler = new HashSet<Egitimler>();
            this.Egitmenler = new HashSet<Egitmenler>();
        }
    
        public int SubeNo { get; set; }
        public string SubeAdi { get; set; }
        public string SubeAdresi { get; set; }
        public int EgitmenSayisi { get; set; }
        public int ProgramSayisi { get; set; }
        public int OgrenciNo { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egitimler> Egitimler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egitmenler> Egitmenler { get; set; }
    }
}
